# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='分类名称')),
                ('sort', models.IntegerField(default=0, verbose_name='排序值')),
                ('is_abort', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=500, verbose_name='产品名称')),
                ('image', models.ImageField(upload_to='product/%Y/%m', verbose_name='产品图片')),
                ('barcode', models.CharField(max_length=100, verbose_name='条码')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='成本价')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='售价')),
                ('count', models.IntegerField(default=0, verbose_name='库存')),
                ('is_abort', models.BooleanField(default=False, verbose_name='是否删除')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='分类')),
            ],
        ),
    ]
