# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Goods',
        ),
    ]
