# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170710_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='代购地')),
                ('is_abort', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='buy_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.BuyPlace', verbose_name='代购地'),
        ),
    ]
