# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170720_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
