# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 14:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_goods_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='details',
            field=ckeditor.fields.RichTextField(verbose_name='详情'),
        ),
    ]
