# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170710_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyplace',
            options={'verbose_name': '代购地', 'verbose_name_plural': '代购地'},
        ),
    ]
