# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20170720_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='details',
            field=models.TextField(verbose_name='详情'),
        ),
    ]
