# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='pid',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/%Y/%m', verbose_name='分类图片'),
        ),
    ]
