# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, verbose_name='订单号')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总价')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='收件人')),
                ('mobile', models.CharField(max_length=50, verbose_name='手机')),
                ('address', models.CharField(max_length=500, verbose_name='地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.IntegerField(choices=[(-1, '已关闭'), (0, '待付款'), (1, '待发货'), (2, '待收货'), (3, '已完成')], verbose_name='订单状态')),
                ('remark', models.CharField(max_length=500, verbose_name='备注')),
                ('is_abort', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='售价')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='所属订单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
            },
        ),
    ]
