# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 11:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, verbose_name='订单号')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总价')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='收件人')),
                ('mobile', models.CharField(max_length=50, verbose_name='手机')),
                ('address', models.CharField(max_length=500, verbose_name='地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.IntegerField(choices=[(-1, '已关闭'), (0, '待付款'), (1, '待发货'), (2, '待收货'), (3, '已完成')], verbose_name='订单状态')),
                ('remark', models.CharField(max_length=500, verbose_name='备注')),
                ('is_abort', models.BooleanField(default=False, verbose_name='是否删除')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='客户')),
            ],
            options={
                'verbose_name_plural': '订单',
                'verbose_name': '订单',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='售价')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Goods', verbose_name='产品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='所属订单')),
            ],
            options={
                'verbose_name_plural': '订单详情',
                'verbose_name': '订单详情',
            },
        ),
        migrations.CreateModel(
            name='PayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_no', models.CharField(max_length=100, verbose_name='交易号')),
                ('subject', models.CharField(max_length=1000, verbose_name='交易主题')),
                ('money', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='交易金额')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pay_time', models.DateTimeField(auto_now_add=True, verbose_name='支付时间')),
                ('is_pay', models.BooleanField(default=False, verbose_name='是否支付')),
                ('pay_type', models.IntegerField(choices=[(1, '微信支付'), (2, '支付宝支付'), (3, '余额支付')], verbose_name='支付方式')),
                ('is_abort', models.BooleanField(default=False, verbose_name='是否删除')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='所属订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '支付记录',
                'verbose_name': '支付记录',
            },
        ),
    ]
