# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='收件人'),
        ),
    ]
