# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='prodect',
            new_name='product',
        ),
    ]
