# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 10:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_auto_20170720_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_no', models.CharField(max_length=100, verbose_name='交易号')),
                ('subject', models.CharField(max_length=1000, verbose_name='交易主题')),
                ('money', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='交易金额')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pay_time', models.DateTimeField(auto_now_add=True, verbose_name='支付时间')),
                ('is_pay', models.BooleanField(default=False, verbose_name='是否支付')),
                ('pay_type', models.IntegerField(choices=[(1, '微信支付'), (2, '支付宝支付'), (3, '余额支付')], verbose_name='支付方式')),
                ('is_abort', models.BooleanField(default=False, verbose_name='是否删除')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='所属订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
            },
        ),
    ]
