# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.IntegerField(choices=[(0, '隐藏'), (1, '显示')], verbose_name='状态'),
        ),
    ]
